import type { ArchitectureConfig } from "../config/types.js";

export const START_MARKER = "<!-- archguard:start -->";
export const END_MARKER = "<!-- archguard:end -->";

function list(values: string[] | undefined): string {
  return values?.map((value) => `\`${value}\``).join(", ") ?? "none";
}

export function renderAgentsBlock(config: ArchitectureConfig): string {
  const layers = Object.entries(config.layers)
    .map(([name, rule]) => {
      const paths = Array.isArray(rule.path) ? rule.path.join(", ") : rule.path;
      return [
        `### ${name}`,
        "",
        rule.description,
        "",
        `- Paths: ${paths}`,
        `- May call: ${list(rule.can_call)}`,
        `- Must not call: ${list(rule.cannot_call)}`,
        `- Must not import: ${list(rule.cannot_import)}`,
      ].join("\n");
    })
    .join("\n\n");

  return [
    START_MARKER,
    "## ArchGuard Architecture Contract",
    "",
    "_This section is generated by `archguard agents generate`. Edit `.archguard/architecture.yaml` instead._",
    "",
    `Project: **${config.architecture.name}**`,
    `Pattern: **${config.architecture.pattern}**`,
    `Language: **${config.architecture.language}**`,
    config.architecture.framework
      ? `Framework: **${config.architecture.framework}**`
      : undefined,
    "",
    "Follow these dependency boundaries when adding or changing code.",
    "",
    layers,
    END_MARKER,
  ]
    .filter((line) => line !== undefined)
    .join("\n");
}

export function updateManagedBlock(existing: string, block: string): string {
  const start = existing.indexOf(START_MARKER);
  const end = existing.indexOf(END_MARKER);

  if (start === -1 && end === -1) {
    const prefix = existing.trimEnd();
    return `${prefix ? `${prefix}\n\n` : ""}${block}\n`;
  }

  if (start === -1 || end === -1 || end < start) {
    throw new Error("AGENTS.md contains an incomplete ArchGuard managed block.");
  }

  const before = existing.slice(0, start).trimEnd();
  const after = existing.slice(end + END_MARKER.length).trimStart();
  return `${before ? `${before}\n\n` : ""}${block}${after ? `\n\n${after}` : "\n"}`;
}
